### ISSUE TITLE
MC startup crash on jdk >=15

### ISSUE THREAD

**Issue by wehttvM** [cpw/grossjava9classpathhacks#1]
The URL "hack" seems to be broken on JDK versions greater than 15.

```
15:14:33.677 game java.lang.NoSuchFieldException: ucp
15:14:33.677 game at java.base/java.lang.Class.getDeclaredField(Class.java:2553)
15:14:33.677 game at cpw.mods.gross.Java9ClassLoaderUtil.getSystemClassPathURLs(Java9ClassLoaderUtil.java:28)
15:14:33.678 game at cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:139)
15:14:33.682 game at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
15:14:33.682 game at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
15:14:33.682 game Exception in thread "main" java.lang.NullPointerException: Cannot read the array length because "urls" is null
15:14:33.682 game at java.base/jdk.internal.loader.URLClassPath.<init>(URLClassPath.java:153)
15:14:33.682 game at java.base/jdk.internal.loader.URLClassPath.<init>(URLClassPath.java:174)
15:14:33.682 game at java.base/java.net.URLClassLoader.<init>(URLClassLoader.java:149)
15:14:33.682 game at cpw.mods.modlauncher.TransformationServicesHandler$TransformerClassLoader.<init>(TransformationServicesHandler.java:159)
15:14:33.682 game at cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:139)
15:14:33.682 game at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
15:14:33.682 game at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```

**Comment by cpw** [comment]
Fixed
